name: Trudy Graham
favicon: null
layout_spectrum: 0.4579464450944215
typography_spectrum: 0.9175124634057283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e8eb'
    - '#c6ab8a'
    - '#804028'
    - '#2c2c2a'
    - '#6e7057'
  brandStrength: 0.8125
  lightness: 0.8952405543532223
  saturation: 0.8201443664729595
  rhythmicContrast: 0.47403411380946636
purpose: []
